# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CSMOA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo chmod 777 chromedriver
        sudo apt-get install -y chromium-browser
        python -m pip install --upgrade pip
        pip install pytz
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start Crawling
      run: |
        python main.py
      env:
        DB_INFO: ${secrets.DB_INFO}
        MY_GITHUB_TOKEN: ${secrets.MY_GITHUB_TOKEN}
